name: Fetch Docker Image

on:
  push:
    branches:
      - main

jobs:
  fetch-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull the Docker image
        run: docker pull my-docker-image:latest

      - name: Run the Docker container
        run: docker run --rm my-docker-image:latest
